{% set name = "msgspec" %}
{% set version = "0.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b252174d33c7d7885e5efe8009147f09da4bf6655b86dba9128a2a4d4c1fb6ee

build:
  number: 0

outputs:
  - name: msgspec
    version: {{ version }}
    build:
      skip: true  # [py<38]
      script: python -m pip install . -vv
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - {{ compiler('c') }}
      host:
        - python
        - pip
      run:
        - python
    test:
      imports:
        - msgspec

  - name: msgspec-yaml
    version: {{ version }}
    requirements:
      run:
        - {{ pin_subpackage(name) }}
        - pyyaml
    test:
      imports:
        - msgspec

  - name: msgspec-toml
    version: {{ version }}
    requirements:
      run:
        - {{ pin_subpackage(name) }}
        - tomli    # [py<311]
        - tomli-w
    test:
      imports:
        - msgspec

about:
  home: https://jcristharif.com/msgspec/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: |
    A fast serialization and validation library, with builtin support for JSON,
    MessagePack, YAML, and TOML.
  description: |
    `msgspec` is a fast serialization and validation library for Python,
    supporting JSON, MessagePack, YAML, and TOML. It integrates well with
    Python's type annotations, providing ergonomic (and performant!) schema
    validation.
  doc_url: https://jcristharif.com/msgspec/
  dev_url: https://github.com/jcrist/msgspec

extra:
  recipe-maintainers:
    - jcrist
